vm_memory_high_watermark.relative = 0.75
vm_memory_high_watermark_paging_ratio = 0.75

disk_free_limit.absolute = 1GB

channel_max = 128
heartbeat = 60

queue_master_locator = min-masters

log.console = true
log.console.level = warning
log.file = false

collect_statistics_interval = 10000
