name: Deploy to Production

on:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 46.226.165.102
          username: root
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /root/budget-tg-manager-app
            git pull
            docker compose -f docker-compose.prod.yaml down
            docker compose -f docker-compose.prod.yaml up -d --build
            docker compose -f docker-compose.prod.yaml ps
